name: quicksale_pos
description: "A Point of Sale application for small businesses."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core packages for QuickSale POS
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  intl: ^0.19.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  
  # Feature packages
  mobile_scanner: ^5.1.1
  pdf: ^3.11.0
  printing: ^5.12.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true